name: Release
on:
  push:
    tags: ["v*"]
jobs:
  release:
    uses: Doryski/release/.github/workflows/release.yml@v1
    permissions:
      contents: write
      id-token: write
    with:
      run-lint: false
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
